version: "3.9"

services:
  worker:
    build: .
    env_file:
      - .env
    environment:
      - RABBITMQ_HOST=queue
      - POSTGRES_HOST=database
    depends_on:
      - database
      - queue

  database:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - database:/var/lib/postgresql/data
      - ./.docker/database:/docker-entrypoint-initdb.d

  queue:
    image: rabbitmq:3
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    volumes:
      - queue:/var/lib/rabbitmq

volumes:
  database:
  queue:
