CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
    );

START TRANSACTION;

CREATE TABLE "Users" (
                         "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                         "ProviderId" text NOT NULL,
                         "Username" text NOT NULL,
                         "Email" text NOT NULL,
                         "DisplayName" text NOT NULL,
                         "AvatarUrl" text NOT NULL,
                         CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "Kweks" (
                         "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                         "UserId" integer NOT NULL,
                         "Text" text NOT NULL,
                         "PostedAt" timestamp with time zone NOT NULL,
                         CONSTRAINT "PK_Kweks" PRIMARY KEY ("Id"),
                         CONSTRAINT "FK_Kweks_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Kweks_UserId" ON "Kweks" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220504191046_InitialCreate', '6.0.4');

COMMIT;
